### ISSUE TITLE
BUG: PostReadReceiptRequest optionality is incorrect

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#83]
Reviewing the latest generated code:

```YAML
    - !<!ObjectSchema> &ref_61
      type: object
      apiVersions:
        - !<!ApiVersion> 
          version: 2020-07-20-preview1
      properties:
        - !<!Property> 
          schema: *ref_5
          required: true
          serializedName: clientMessageId
        - !<!Property> 
          schema: *ref_6
          required: true
          serializedName: messageId
      language: !<!Languages> 
        default:
          name: PostReadReceiptRequest
          description: ''
          namespace: ''
      protocol: !<!Protocols> {}
```

These properties are both required. However, the generated code shows:

```Swift
    /// The client message Id specified when the message was sent.
/// This Id is a client-specific Id in a numeric unsigned Int64 format. It can be used for client deduping, among other client usages.
    public let clientMessageId: String?
    
    /// Id of the latest message read by current user.
    public let messageId: String?
```

So the logic setting the optionality in the ViewModel is likely incorrect.
